<center><h1> Corréction Série de Travaux Pratiques N° 6 - Machine Learning </h1></center>
<center><h2> Regression Logistique</h2></center>

---



# **Partie I : Regression Logistique**

Vous trouverez ci-joint un exemple d'utilisation d'algorithme de regréssion logistique avec les quatres étapes principales.

In [8]:
# Step 1: Import packages, functions
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Get data
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])

# Step 3: Create a model and train it
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0, max_iter=100)
model.fit(x, y)

# Step 4: Evaluate the model
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score_ = model.score(x, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

In [9]:
print('x:', x)
print('y:', y)
print('intercept:', model.intercept_)
print('coef:', model.coef_)
print('p_pred:', p_pred)
print('y_pred:', y_pred)
print('score_:', score_)
print('conf_m:', conf_m)
print('report:', report)

x: [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
y: [0 1 0 0 1 1 1 1 1 1]
intercept: [-1.51632619]
coef: [[0.703457]]
p_pred: [[0.81999686 0.18000314]
 [0.69272057 0.30727943]
 [0.52732579 0.47267421]
 [0.35570732 0.64429268]
 [0.21458576 0.78541424]
 [0.11910229 0.88089771]
 [0.06271329 0.93728671]
 [0.03205032 0.96794968]
 [0.0161218  0.9838782 ]
 [0.00804372 0.99195628]]
y_pred: [0 0 0 1 1 1 1 1 1 1]
score_: 0.8
conf_m: [[2 1]
 [1 6]]
report:               precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10



# **Partie II : Classification Binaire**

L'objectif de l'ensemble de données "**diabetes.csv**" est de prédire, sur la base de mesures diagnostiques, si un patient **souffre de diabète ou pas**.

Ce dataset contient les caractéristiques suivants

**Grossesses**: Nombre de fois enceintes.

**Glucose**: concentration plasmatique de glucose à 2 heures lors d'un test oral de tolérance au glucose.

**Pression artérielle** : tension artérielle diastolique (mm Hg).

**Épaisseur de la peau** : épaisseur du pli cutané du triceps (mm).

**Insuline** : insuline sérique de 2 heures (mu U/ml).

**IMC** : Indice de masse corporelle (poids en kg/(taille en m)^2).

**DiabetesPedigreeFunction** : fonction généalogique du diabète.

**Âge** : Âge (ans).

**Résultat** : variable de classe (0 ou 1).

### **Questions :**

Étape 1 : Importer et afficher et explorer l'ensemble de données "**diabetes.csv**"

Étape 2 : Créer dépendante d'une variable indépendante et stockée sur les variables X et Y.

Étape 3 : Transformer les chaînes en entier.

Étape 4 : Divisez les données en ensembles d'entrainement et de test.

Étape 5 : Définir l'algorithme de régression logistique.

Étape 6 :Tester les données de test en utilisant votre modèle.

Étape 7 : Évaluation du modèle.

Étape 8 : Prédire avec de nouvelles valeurs.

In [27]:
# # Se connecter
# from google.colab import drive
# drive.mount('/content/drive')
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


dataset = read_csv("diabetes.csv")
dataset.head()
x = dataset[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']]
# x = dataset.drop("Outcome", axis=1)
y = dataset['Outcome']

In [43]:
# cd drive/My Drive/Colab Notebooks

# Notes:
# Precesion = VP/(VP+FP) -> Dans tous les cas positives, combien son reelement positive
# Recall = VP/(VP+FN) -> Dans tous les cas reelement positives, combien le model a predire correctement
label_encoder = LabelEncoder()
x_encoded = x.apply(label_encoder.fit_transform)
x_train, x_test, y_train, y_test = train_test_split(x_encoded, y, test_size=0.33)
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()
lr_model.fit(x_train, y_train)

ValueError: Found input variables with inconsistent numbers of samples: [768, 254]

In [35]:
# Binary Classification : Diabetes
lr_model.predict(x_test)
lr_model.score(x_test, y_test)

0.8188976377952756

# **Partie II : Classification Multi-Classe**

Pour cette partie, on utilisera le **dataset IRIS**. Ce dernier est une base de données regroupant les caractéristiques de **trois espèces de fleurs d’Iris, à savoir Setosa, Versicolour et Virginica**. Chaque ligne de ce jeu de données est une observation des caractéristiques d’une fleur d’Iris. Ce dataset décrit les espèces d’Iris par quatre propriétés : longueur et largeur de sépales ainsi que longueur et largeur de pétales. La base de données comporte 150 observations (50 observations par espèce).

### **Questions :**

Étape 1 : Importer, afficher et explorer l'ensemble de données "**iris.csv**"

Étape 2 : Créer dépendante d'une variable indépendante et stockée sur les variables X et Y.

Étape 3 : Transformer les chaînes en entier.

Étape 4 : Divisez les données en ensembles d'entrainement et de test.

Étape 5 : Définir l'algorithme de régression logistique.

Étape 6 :Tester les données de test en utilisant votre modèle.

Étape 7 : Évaluation du modèle.

Étape 8 : Prédire avec de nouvelles valeurs.

In [1]:
# Multi-Class Classification : IRIS Dataset
import pandas as pd

# Charger le fichier CSV
df = pd.read_csv('iris.csv')

# Afficher les premières lignes pour explorer les données
print(df.head())

# Définir les variables indépendantes (features) et la variable dépendante (target)
X = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]
Y = df['variety']

from sklearn.preprocessing import LabelEncoder

# Encoder les étiquettes de la colonne 'variety'
label_encoder = LabelEncoder()
Y_encoded = label_encoder.fit_transform(Y)

from sklearn.model_selection import train_test_split

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_encoded, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression

# Instancier le modèle de régression logistique
model = LogisticRegression(max_iter=200)

# Former le modèle sur les données d'entraînement
model.fit(X_train, Y_train)

# Prédire les étiquettes pour les données de test
Y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Calculer l'accuracy
accuracy = accuracy_score(Y_test, Y_pred)
print(f"Accuracy: {accuracy}")

# Afficher la matrice de confusion
conf_matrix = confusion_matrix(Y_test, Y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Afficher le rapport de classification
class_report = classification_report(Y_test, Y_pred, target_names=label_encoder.classes_)
print("Classification Report:")
print(class_report)

# Exemple de nouvelles valeurs pour prédiction
new_values = [[5.1, 3.5, 1.4, 0.2], [6.7, 3.1, 4.4, 1.4]]

# Prédire les classes des nouvelles valeurs
new_predictions = model.predict(new_values)

# Convertir les prédictions en noms de classes
new_predictions_labels = label_encoder.inverse_transform(new_predictions)
print("New Predictions:", new_predictions_labels)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
Accuracy: 1.0
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        10
  Versicolor       1.00      1.00      1.00         9
   Virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

New Predictions: ['Setosa' 'Versicolor']


/usr/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
